language: python
python:
  - "3.7"
install:
  - virtualenv env --python=python3
  - source env/bin/activate
  - pip install -r requirements.txt
script:
  - pylint bb84 bb84/tests && pytest -v -s --cov=bb84 bb84/tests && ./scripts/run.sh
after_success:
  - codecov
